const IAM_URL = 'https://iam.cloud.ibm.com'
const ACCOUNTS_URL = 'https://accounts.cloud.ibm.com'
const RESOURCE_CONTROLLER_URL = 'https://resource-controller.cloud.ibm.com'
const GLOBAL_CATALOG_URL = 'https://globalcatalog.cloud.ibm.com'
const IAM_OPENID_CONFIG_CACHE_TIMEOUT = 3600000
const RESOURCE_SERVICE_CACHE_TIMEOUT = 30000
const GLOBAL_CATALOG_API_CACHE_TIMEOUT = 3600000

const IBMID_APIKEY_LOGIN_CACHE_TIMEOUT = 1200000

module.exports = {
    IAM_URL,
    ACCOUNTS_URL,
    RESOURCE_CONTROLLER_URL,
    GLOBAL_CATALOG_URL,
    RESOURCE_SERVICE_CACHE_TIMEOUT,
    GLOBAL_CATALOG_API_CACHE_TIMEOUT,
    IAM_OPENID_CONFIG_CACHE_TIMEOUT,
    
    IBMID_APIKEY_LOGIN_CACHE_TIMEOUT
}